version: '3.9'

networks:
    recursive-network:

services:
    recursive-backend:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: recursive-backend
        image: recursive-backend:development
        ports:
            - '8080:80'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - .:/var/www
            - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - recursive-network
