version: '3.9'

networks:
    recursive-network:

services:
    recursive-backend-development:
        build:
            context: ../../
            dockerfile: .docker/development/Dockerfile.dev
        container_name: recursive-backend
        image: recursive-backend:development
        ports:
            - '8080:80'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ../../:/var/www
            - ../../.docker/development/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ../../.docker/development/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        environment:
            - NODE_ENV=development
        networks:
            - recursive-network
